package com.sundevs.comicbook.utils

const val ARGUMENT_DESCRIPTION = "ARGUMENT_DESCRIPTION"
const val ARGUMENT_DISMISS = "ARGUMENT_DISMISS"
const val ARGUMENT_TITLE = "ARGUMENT_TITLE"

const val ARGUMENT_COMIC_DETAIL = "COMIC_DETAIL"

const val COUNT_GRID_MODE = 3
const val COUNT_LIST_MODE = 1
